version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: conceptnet
      POSTGRES_USER: conceptnet
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  conceptnet:
    container_name: conceptnet
    image: bwulff/conceptnet-runtime
    entrypoint: /run_conceptnet_${CONCEPTNET_ENTRYPOINT}.sh
    environment:
      - CONCEPTNET_DB_HOSTNAME=db
      - CONCEPTNET_DB_PORT=5432
      - CONCEPTNET_DB_NAME=conceptnet
      - CONCEPTNET_DB_USER=conceptnet
      - CONCEPTNET_DB_PASSWORD=conceptnet
    volumes:
      - ./data/conceptnet:/opt/conceptnet5/data
    ports:
      - 8080:8084


