version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: conceptnet
      POSTGRES_USER: conceptnet
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  conceptnet:
    image: bwulff/conceptnet-runtime
    entrypoint: /run_conceptnet_${CONCEPTNET_ENTRYPOINT}.sh
    volumes:
      - ./conceptnet-data:/opt/conceptnet5/data


